"use strict";
var __assign =
  (this && this.__assign) ||
  function () {
    __assign =
      Object.assign ||
      function (t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
          s = arguments[i];
          for (var p in s)
            if (Object.prototype.hasOwnProperty.call(s, p)) t[p] = s[p];
        }
        return t;
      };
    return __assign.apply(this, arguments);
  };
exports.__esModule = true;
var jsx_runtime_1 = require("react/jsx-runtime");
var head_1 = require("next/head");
function Home() {
  return (0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, {
    children: [
      (0, jsx_runtime_1.jsxs)(head_1["default"], {
        children: [
          (0, jsx_runtime_1.jsx)("title", { children: "Create Next App" }),
          (0, jsx_runtime_1.jsx)("meta", {
            name: "description",
            content: "Generated by create next app",
          }),
          (0, jsx_runtime_1.jsx)("link", { rel: "icon", href: "/favicon.ico" }),
        ],
      }),
      (0, jsx_runtime_1.jsx)("div", {
        children: (0, jsx_runtime_1.jsx)(
          "h1",
          __assign(
            { className: "text-4xl font-bold text-blue-600" },
            { children: "Installing Tailwind CSS" },
          ),
        ),
      }),
    ],
  });
}
exports["default"] = Home;
